#ifndef CLKS_SYSCALL_H
#define CLKS_SYSCALL_H

#include <clks/types.h>

#define CLKS_SYSCALL_LOG_WRITE           0ULL
#define CLKS_SYSCALL_TIMER_TICKS         1ULL
#define CLKS_SYSCALL_TASK_COUNT          2ULL
#define CLKS_SYSCALL_CURRENT_TASK_ID     3ULL
#define CLKS_SYSCALL_SERVICE_COUNT       4ULL
#define CLKS_SYSCALL_SERVICE_READY_COUNT 5ULL
#define CLKS_SYSCALL_CONTEXT_SWITCHES    6ULL
#define CLKS_SYSCALL_KELF_COUNT          7ULL
#define CLKS_SYSCALL_KELF_RUNS           8ULL
#define CLKS_SYSCALL_FS_NODE_COUNT       9ULL
#define CLKS_SYSCALL_FS_CHILD_COUNT      10ULL
#define CLKS_SYSCALL_FS_GET_CHILD_NAME   11ULL
#define CLKS_SYSCALL_FS_READ             12ULL
#define CLKS_SYSCALL_EXEC_PATH           13ULL
#define CLKS_SYSCALL_EXEC_REQUESTS       14ULL
#define CLKS_SYSCALL_EXEC_SUCCESS        15ULL
#define CLKS_SYSCALL_USER_SHELL_READY    16ULL
#define CLKS_SYSCALL_USER_EXEC_REQUESTED 17ULL
#define CLKS_SYSCALL_USER_LAUNCH_TRIES   18ULL
#define CLKS_SYSCALL_USER_LAUNCH_OK      19ULL
#define CLKS_SYSCALL_USER_LAUNCH_FAIL    20ULL

void clks_syscall_init(void);
u64 clks_syscall_dispatch(void *frame_ptr);
u64 clks_syscall_invoke_kernel(u64 id, u64 arg0, u64 arg1, u64 arg2);

#endif
